export const SET_PRODUCTS = "SET_PRODUCTS";
export const FETCHING_PRODUCTS = " FETCHING_PRODUCTS"
export const DETAILED_PRODUCT = " DETAILED_PRODUCT "
export const SELECTED_PRODUCTS = " SELECTED_PRODUCT";
export const REMOVE_PRODUCTS = " REMOVE_PRODUCT";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
